FROM docker.io/library/ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    bc bison build-essential clang cpio flex libelf-dev libssl-dev lld llvm \
    make perl python3 xz-utils && \
    rm -rf /var/lib/apt/lists/*
